/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kartupasien;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Angga
 */
public class dataPasien extends javax.swing.JDialog {

    formRecordPasien f;
    MainForm parent;
    public int idPasien;
    public int mode;
    public static final int UPDATE=0;
    public static final int INSERT=1;
    public static final int SHOW=2;
    private List<Object[]> rowTambahan = new ArrayList();
    private List<Object[]> rowDelete = new ArrayList();
    private List rowIDNew = new ArrayList();
   
    private int idbarisbaru=0;
    
    
    database db;
    private String[] identitasPasien;
    /**
     * Creates new form dataPasien
     */
    public dataPasien(MainForm parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(parent);
        db = new database(parent);
        
        
    }
    
    public void setData(){
        if(this.mode == dataPasien.UPDATE){
           
            this.identitasPasien = db.ambilDataPasien(this.idPasien);
            ed_nama_pasien.setText(this.identitasPasien[0]);
            txt_alamat.setText(this.identitasPasien[1]);
            ed_umur.setText(this.identitasPasien[2]);
            if(this.identitasPasien[3].compareTo("Laki-Laki")==0){
                cb_kelamin.setSelectedIndex(0);
            }else{
                cb_kelamin.setSelectedIndex(1);
            }
            ed_nama_pasien.setEditable(false);
            txt_alamat.setEditable(false);
            ed_umur.setEditable(false);
            cb_kelamin.setEnabled(false);
            
            cb_kelamin.setBackground(Color.white);
            cb_kelamin.setForeground(Color.white);
            ed_nama_pasien.setBackground(Color.white);
            ed_umur.setBackground(Color.white);
            
            Thread load = new Thread(new worker(worker.TABELRIWAYATPASIEN, this, this.db,this.idPasien));
            load.start();
            
            
                        
             
            
        }else if(this.mode == dataPasien.SHOW){
            btn_simpan_datapasien.setVisible(false);
        }else if(this.mode == dataPasien.INSERT){
            Object[] col = new Object[]{"ID","tanggal","diagnose","obat","tindakan","keterangan"};
            DefaultTableModel dm = new DefaultTableModel(col, 0);            
            tabel_riwayat.setModel(dm);
            btn_chooser.setEnabled(false);
            
        }
    }
    
    
    public void tambahbaris(String tanggal,String diagnose,String obat,String tindakan,String keterangan,char tipegigi,String gigi,int harga,Image img){
        if(this.idbarisbaru==0){
               this.idbarisbaru = db.notterakhir()+1;
        }else{
            this.idbarisbaru++;
        }
        DefaultTableModel dm = (DefaultTableModel)tabel_riwayat.getModel();
       
        rowTambahan.add(new Object[]{this.idbarisbaru,this.idPasien,tanggal,diagnose,obat,tindakan,keterangan,tipegigi,gigi,harga,img});
        rowIDNew.add(this.idbarisbaru);
        
            dm.addRow(new Object[]{this.idbarisbaru,tanggal,diagnose,obat,tindakan,keterangan,tipegigi,harga});
        
        tabel_riwayat.setModel(dm);
    
    }
    
    
    public void setIdPasien(int idpasien){
        for(int i=0;i<rowTambahan.size();i++){
            rowTambahan.get(i)[1] = idpasien;
        }
    }
    
   
    private Object cariObject(int id_baris){
        for(int i=0;i<rowTambahan.size();i++){
            if(rowTambahan.get(i)[0].equals(id_baris))
                return rowTambahan.get(i);
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btn_tambah_record = new javax.swing.JButton();
        btn_hapus_record = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_riwayat = new javax.swing.JTable(){
            public boolean isCellEditable(int rowindex,int colindex){
                return false;
            }
        };
        lbl_status = new javax.swing.JLabel();
        btn_chooser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ed_umur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_kelamin = new javax.swing.JComboBox();
        ed_nama_pasien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_simpan_datapasien = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Pasien");
        setResizable(false);

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane2.setViewportView(txt_alamat);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_tambah_record.setText("Tambah record");
        btn_tambah_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_recordActionPerformed(evt);
            }
        });

        btn_hapus_record.setText("Hapus Record");
        btn_hapus_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_recordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Riwayat Kesehatan");

        tabel_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabel_riwayat.setRowHeight(30);
        tabel_riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_riwayatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_riwayat);

        btn_chooser.setText("Export ke *.docx");
        btn_chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooserActionPerformed(evt);
            }
        });

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_status)
                        .addGap(78, 78, 78)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_chooser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_tambah_record)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus_record))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_status)
                    .addComponent(btn_chooser)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_record)
                    .addComponent(btn_hapus_record))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Alamat");

        jLabel3.setText("Umur");

        jLabel2.setText("Kelamin");

        cb_kelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));

        ed_nama_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_nama_pasienActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        btn_simpan_datapasien.setText("Simpan Data Pasien");
        btn_simpan_datapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_datapasienActionPerformed(evt);
            }
        });

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_simpan_datapasien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_close))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ed_umur)
                                    .addComponent(cb_kelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ed_nama_pasien)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(228, 228, 228))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ed_nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ed_umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan_datapasien)
                    .addComponent(btn_close))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_recordActionPerformed
        // TODO add your handling code here:
        
        f = new formRecordPasien(this.parent,this, true);
        f.mode = formRecordPasien.INSERT;
        f.setData();
        f.setVisible(true);
        
    }//GEN-LAST:event_btn_tambah_recordActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
       if(this.rowTambahan.size()>0) {
            int option = JOptionPane.showConfirmDialog(this, "Apa anda ingin menyimpan data riwayat yang baru saja ditambah?","Konfirmasi Penyimpanan Riwayat" , JOptionPane.YES_NO_OPTION);
           if(option==JOptionPane.YES_OPTION){
               if(this.mode == dataPasien.UPDATE){
                    db.tambahRiwayatpasien(this.rowTambahan);
                     TableModel tm = db.ambilDataPasien("");
                     this.parent.refreshdatatabel(tm);
               }
                this.dispose();
           }else if(option==JOptionPane.NO_OPTION){
                this.dispose();
           }
       }else{
             this.dispose();
       }
        
       
        
    }//GEN-LAST:event_btn_closeActionPerformed

    private void tabel_riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_riwayatMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            f = new formRecordPasien(this.parent,this, true);
            
            int id_riwayat = (Integer)tabel_riwayat.getModel().getValueAt(tabel_riwayat.getSelectedRow(), 0);
            if(this.rowIDNew.contains(id_riwayat)){                
               // f.mode = formRecordPasien.UPDATE;
            } else{
               f.mode = formRecordPasien.SHOW;
               f.id_riwayat = id_riwayat;           
            f.setData();
            f.setVisible(true);
            }
            
        }
        
    }//GEN-LAST:event_tabel_riwayatMouseClicked

    private void btn_simpan_datapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_datapasienActionPerformed
        // TODO add your handling code here:
        if(this.mode == dataPasien.INSERT){
            
            try{
                String nama = ed_nama_pasien.getText();
                String alamat = txt_alamat.getText();
                int umur = Integer.parseInt(ed_umur.getText());
                String kelamin = (String)cb_kelamin.getSelectedItem();
                
                if(nama.compareTo("")==0 || alamat.compareTo("")==0 || kelamin.compareTo("")==0){
                   JOptionPane.showMessageDialog(this.parent,"Silahkan diisi identitas pasien dengan lengkap");
                }else{
                
                    db.tambahdatapasien(nama, alamat, umur, kelamin); 
                    setIdPasien(db.notterakhirpasien());
                    db.tambahRiwayatpasien(this.rowTambahan);
                    TableModel tm = db.ambilDataPasien("");
                    
                    this.parent.refreshdatatabel(tm);
                    dispose();
                }
            }catch(NumberFormatException ne){
                JOptionPane.showMessageDialog(this.parent, "Umur harus angka");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this.parent,ex);
            }finally{
                
            }
        }else if(this.mode == dataPasien.UPDATE){
            try{      
                
                
                db.tambahRiwayatpasien(this.rowTambahan);
                TableModel tm = db.ambilDataPasien("");
                this.parent.refreshdatatabel(tm);
                dispose();
            }catch(NumberFormatException ne){
                JOptionPane.showMessageDialog(this.parent, "Umur harus angka");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this.parent,ex);
            }finally{
                
            }
        }
        
        
        
    }//GEN-LAST:event_btn_simpan_datapasienActionPerformed

    private void btn_hapus_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_recordActionPerformed
        // TODO add your handling code here:
       try{
        int id_riwayat = (Integer)tabel_riwayat.getModel().getValueAt(tabel_riwayat.getSelectedRow(), 0);
        
            if(rowIDNew.contains(id_riwayat)){
                DefaultTableModel dtm = (DefaultTableModel)tabel_riwayat.getModel();
                dtm.removeRow(tabel_riwayat.getSelectedRow());
                rowTambahan.remove(cariObject(id_riwayat));
                if(this.idbarisbaru>0 && this.idbarisbaru==id_riwayat)
                    this.idbarisbaru--;
            }else{
                JOptionPane.showMessageDialog(this.parent, "Data riwayat Kesehatan tersebut sudah tercatat sebelumnya dan tidak bisa dihapus");
            }
            
       }catch(ArrayIndexOutOfBoundsException ar){
           JOptionPane.showMessageDialog(this.parent, "Silahkan Pilih data yang baru saja ditambahkan karena data riwayat pasien yang sudah tercatat tidak bisa di hapus");
           
       }
        
            
        
    }//GEN-LAST:event_btn_hapus_recordActionPerformed

    private void ed_nama_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_nama_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ed_nama_pasienActionPerformed

    private void btn_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooserActionPerformed
        // TODO add your handling code here:
        this.fc = new JFileChooser("d:\\");
        int stat = fc.showSaveDialog(this.parent);
        if(stat == JFileChooser.APPROVE_OPTION){
            
            fc.approveSelection();      
            Thread t = new Thread(new worker(this.idPasien, worker.EXPORT, fc.getSelectedFile().getPath(),this.db));
             t.start();
        }else{
           
        }
        
    }//GEN-LAST:event_btn_chooserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        Thread t = new Thread(new worker(worker.REPORT,this,this.db,this.idPasien));
             t.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private javax.swing.JFileChooser fc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chooser;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_hapus_record;
    private javax.swing.JButton btn_simpan_datapasien;
    private javax.swing.JButton btn_tambah_record;
    private javax.swing.JComboBox cb_kelamin;
    private javax.swing.JTextField ed_nama_pasien;
    private javax.swing.JTextField ed_umur;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbl_status;
    public javax.swing.JTable tabel_riwayat;
    private javax.swing.JTextArea txt_alamat;
    // End of variables declaration//GEN-END:variables
}
