/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kartupasien;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Angga
 */
public class formRecordPasien extends javax.swing.JDialog {

    /**
     * Creates new form formRecordPasien
     */
    public int mode;
    public int id_riwayat;
    public static final int UPDATE=0;
    public static final int INSERT=1;
    public static final int SHOW=2;
    database db;
    MainForm parent;
    dataPasien parent2;
    
    
    public formRecordPasien(MainForm parent,dataPasien parent2, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.parent2 = parent2;
		db = new database((parent));
        initComponents();
        
        setLocationRelativeTo(parent);
        
    }
    
    public void setData(){
        
        if(this.mode == formRecordPasien.UPDATE){
           
          String[] data = db.ambilDataRiwayatPasien(this.id_riwayat);
         
          lbl_tanggal.setVisible(false);
          ed_tanggal.setVisible(false);
          
          txt_diagnose.setText(data[1]);
          txt_obat.setText(data[2]);
          txt_tindakan.setText(data[3]);
          txt_keterangan.setText(data[4]);
          
          
        
            
        }else if(this.mode == formRecordPasien.SHOW){
           this.btn_tambah_riwayat.setVisible(false);
           String[] data = db.ambilDataRiwayatPasien(this.id_riwayat);
			String[] datagigi = db.ambilDataGigi(this.id_riwayat);
			if(datagigi[0]!=null){
				if(datagigi[0].equals("D")){
					jPanel2.setTipeGigi(DiagramGigi.DEWASA,datagigi[1]);	
					cb_tipegigi.setSelectedIndex(0);
				}if(datagigi[0].equals("A")){
					jPanel2.setTipeGigi(DiagramGigi.ANAK,datagigi[1]);
					cb_tipegigi.setSelectedIndex(1);
				}if(datagigi[0].equals("T")){
					jPanel2.setTipeGigi(DiagramGigi.TRANSISI,datagigi[1]);
					cb_tipegigi.setSelectedIndex(2);
				}
			}
        jPanel2.locating();        
		jPanel2.repaint();		
	
		ed_harga.setText(data[5]);	
		ed_tanggal.setText(data[0]);
		ed_harga.setEditable(false);
		cb_tipegigi.setEnabled(false);
          txt_diagnose.setText(data[1]);
          txt_obat.setText(data[2]);
          txt_tindakan.setText(data[3]);
          txt_keterangan.setText(data[4]);
          
		  
          txt_diagnose.setEditable(false);
            txt_obat.setEditable(false);
            txt_tindakan.setEditable(false);
            txt_keterangan.setEditable(false);
            
            cb_tipegigi.setBackground(Color.white);
			ed_harga.setBackground(Color.white);
			txt_diagnose.setBackground(Color.white);
            txt_obat.setBackground(Color.white);
            txt_tindakan.setBackground(Color.white);
            txt_keterangan.setBackground(Color.white);
        }else if(this.mode == formRecordPasien.INSERT){
		
			jPanel2.setTipeGigi(DiagramGigi.DEWASA,null);
			jPanel2.locating();
			jPanel2.addComp();
			jPanel2.repaint();	
				lbl_tanggal.setVisible(false);
			  ed_tanggal.setVisible(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_diagnose = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_obat = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_tindakan = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_keterangan = new javax.swing.JTextArea();
        btn_tambah_riwayat = new javax.swing.JButton();
        btn_close_riwayat = new javax.swing.JButton();
        lbl_tanggal = new javax.swing.JLabel();
        ed_tanggal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new DiagramGigi(this);
        jLabel6 = new javax.swing.JLabel();
        cb_tipegigi = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ed_harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Diagnose");

        jLabel3.setText("Obat Yang diberikan");

        jLabel4.setText("Tindakan");

        jLabel5.setText("Keterangan");
		
		
		
		

        txt_diagnose.setColumns(20);
        txt_diagnose.setRows(5);
        jScrollPane1.setViewportView(txt_diagnose);

        txt_obat.setColumns(20);
        txt_obat.setRows(5);
        jScrollPane2.setViewportView(txt_obat);

        txt_tindakan.setColumns(20);
        txt_tindakan.setRows(5);
        jScrollPane3.setViewportView(txt_tindakan);

        txt_keterangan.setColumns(20);
        txt_keterangan.setRows(5);
        jScrollPane4.setViewportView(txt_keterangan);

        btn_tambah_riwayat.setText("Simpan Riwayat Pasien");
        btn_tambah_riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_riwayatActionPerformed(evt);
            }
        });

        btn_close_riwayat.setText("Close");
        btn_close_riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_close_riwayatActionPerformed(evt);
            }
        });

        lbl_tanggal.setText("Tanggal dan Jam");

        ed_tanggal.setEditable(false);
        ed_tanggal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Kerusakan Gigi");

        

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        jLabel6.setText("Tipe Gigi");

        cb_tipegigi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dewasa", "Anak-anak", "Transisi" }));
        cb_tipegigi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipegigiItemStateChanged(evt);
            }
        });
        cb_tipegigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipegigiActionPerformed(evt);
            }
        });

        jLabel7.setText("Harga");

        jLabel8.setText("Rp");

        jLabel9.setText("(Tanpa tanda koma dan titik)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(39, 39, 39)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(26, 26, 26)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_tipegigi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(335, 335, 335)
                            .addComponent(btn_tambah_riwayat)
                            .addGap(27, 27, 27)
                            .addComponent(btn_close_riwayat)
                            .addGap(15, 15, 15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tanggal)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ed_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addComponent(ed_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tanggal)
                    .addComponent(ed_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(ed_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane4)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipegigi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_riwayat)
                    .addComponent(btn_close_riwayat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_close_riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_close_riwayatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btn_close_riwayatActionPerformed

    private void btn_tambah_riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_riwayatActionPerformed
            // TODO add your handling code here:
        
        Calendar today = Calendar.getInstance();
        Date now = today.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String sekarang = sdf.format(now);
        
        if(txt_diagnose.getText().compareTo("")==0 || txt_obat.getText().compareTo("")==0 || txt_tindakan.getText().compareTo("")==0){
            JOptionPane.showMessageDialog(this.parent, "Silahkan diisi data riwayat pasien dengan lengkap");
        }else{
            try{
                int harga = Integer.parseInt(ed_harga.getText());
                Image img = new BufferedImage(jPanel2.getWidthMax(),jPanel2.getheightMax(), BufferedImage.TYPE_BYTE_BINARY);
                jPanel2.paintComponent(img.getGraphics());
               
            this.parent2.tambahbaris(sekarang,txt_diagnose.getText(),txt_obat.getText(),txt_tindakan.getText()
                    ,txt_keterangan.getText(),this.jPanel2.getInformasiTipeGigi(),this.jPanel2.getInformasiGigi(),harga,img);
            dispose();
            }catch(NumberFormatException ne){
                JOptionPane.showMessageDialog(this.parent, "Harga harus angka tanpa koma atau titik");
            }
        }
    }//GEN-LAST:event_btn_tambah_riwayatActionPerformed

    private void cb_tipegigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipegigiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_tipegigiActionPerformed

    private void cb_tipegigiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipegigiItemStateChanged
        // TODO add your handling code here:
		if(this.mode==INSERT){
			if(cb_tipegigi.getSelectedIndex()==0){
				this.jPanel2.setTipeGigi(DiagramGigi.DEWASA,null);
				this.jPanel2.locating();
				this.jPanel2.addComp();
			}else if(cb_tipegigi.getSelectedIndex()==1){
				 this.jPanel2.setTipeGigi(DiagramGigi.ANAK,null);
				 this.jPanel2.locating();
				this.jPanel2.addComp();
			}else if(cb_tipegigi.getSelectedIndex()==2){
				 this.jPanel2.setTipeGigi(DiagramGigi.TRANSISI,null);
				 this.jPanel2.locating();
				this.jPanel2.addComp();
			}	 
			this.jPanel2.repaint();
		}
    }//GEN-LAST:event_cb_tipegigiItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close_riwayat;
    private javax.swing.JButton btn_tambah_riwayat;
    private javax.swing.JComboBox cb_tipegigi;
    private javax.swing.JTextField ed_harga;
    private javax.swing.JTextField ed_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    protected DiagramGigi jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JTextArea txt_diagnose;
    private javax.swing.JTextArea txt_keterangan;
    private javax.swing.JTextArea txt_obat;
    private javax.swing.JTextArea txt_tindakan;
    // End of variables declaration//GEN-END:variables
}
