/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kartupasien;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Angga
 */
public class Laporan extends javax.swing.JDialog {

    /**
     * Creates new form Laporan
     */
    private database db;
    private JFileChooser file;
    
    public Laporan(MainForm parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tanggal_awal.setDate(new Date());
        tanggal_akhir.setDate(new Date());
        lbl_total_pendapatan.setText("");
        lbl_total_record.setText("");
        db = new database(parent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tanggal_awal = new com.toedter.calendar.JDateChooser();
        tanggal_akhir = new com.toedter.calendar.JDateChooser();
        btn_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dg_laporan = new javax.swing.JTable(){
            public boolean isCellEditable(int rowindex,int colindex){
                return false;
            }
        };
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbl_total_pendapatan = new javax.swing.JLabel();
        lbl_total_record = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_jumlah_pasien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Laporan");

        jLabel2.setText("Dari tanggal");

        jLabel3.setText("Sampai Tanggal");

        tanggal_awal.setDateFormatString("yyyy-MM-dd");
        tanggal_awal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggal_awalPropertyChange(evt);
            }
        });

        tanggal_akhir.setDateFormatString("yyyy-MM-dd");

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        dg_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dg_laporan);

        jLabel4.setText("Jumlah record ");

        jLabel5.setText("Pendapatan Total ");

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbl_total_pendapatan.setText("jLabel6");

        lbl_total_record.setText("jLabel6");

        jLabel6.setText("Jumlah Pasien");

        lbl_jumlah_pasien.setText("jLabel7");

        jButton1.setText("Simpan Laporan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tanggal_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tanggal_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cari))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_total_pendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_total_record, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_jumlah_pasien))))
                            .addGap(20, 20, 20)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tanggal_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2))
                    .addComponent(tanggal_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_total_record))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_total_pendapatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_jumlah_pasien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tanggal_awalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggal_awalPropertyChange
        // TODO add your handling code here:
        tanggal_akhir.setDate(tanggal_awal.getDate());
        
            tanggal_akhir.setMinSelectableDate(tanggal_awal.getDate());
        
        
    }//GEN-LAST:event_tanggal_awalPropertyChange

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        
        try{
        TableModel dm = db.ambilRentangWaktu(tanggal_awal.getDate(),tanggal_akhir.getDate());
        dg_laporan.setModel(dm);
        
        int[] jml = db.jumlahTotalharga(tanggal_awal.getDate(), tanggal_akhir.getDate());
        lbl_total_record.setText(String.valueOf(jml[1]));
        lbl_total_pendapatan.setText(String.valueOf(jml[0]));
        lbl_jumlah_pasien.setText(String.valueOf(jml[2]));
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_cariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
        String t_awal = sd.format(tanggal_awal.getDate());
        String t_akhir = sd.format(tanggal_akhir.getDate());
        this.file = new JFileChooser();
        
        if(dg_laporan.getModel()!=null){
        int mode = file.showSaveDialog(file);
       
        if(mode == JFileChooser.APPROVE_OPTION){
            
            String path = file.getSelectedFile().getPath()+".docx";
          
            
            
            String[][] hasil = toArrayString(dg_laporan.getModel());
            
           
            
                worker w = new worker(worker.REPORT_KEUANGAN,hasil,t_awal,t_akhir, path, this.db);
             Thread t = new Thread(w);
             t.run();
          
        }
       }else{
            JOptionPane.showConfirmDialog(this, "Tidak ada data dalam tabel");
        }
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private String[][] toArrayString(TableModel tm){
        String[][] hasil = new String[tm.getRowCount()+1][tm.getColumnCount()];
        int kolom = tm.getColumnCount();
        int baris = tm.getRowCount();
        int i=0,j=0;
        for(i=0;i<baris;i++){
            for(j=0;j<kolom;j++){
                hasil[i][j] = String.valueOf(tm.getValueAt(i, j));
            }
        }
        
              
        
       hasil[i][0] = this.lbl_jumlah_pasien.getText();
        hasil[i][1] = this.lbl_total_pendapatan.getText();
        hasil[i][2] = this.lbl_total_record.getText();
        
        
        
        return hasil;
        
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JTable dg_laporan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_jumlah_pasien;
    private javax.swing.JLabel lbl_total_pendapatan;
    private javax.swing.JLabel lbl_total_record;
    private com.toedter.calendar.JDateChooser tanggal_akhir;
    private com.toedter.calendar.JDateChooser tanggal_awal;
    // End of variables declaration//GEN-END:variables
}
